### Арифтметичні операції над Нампай масивами

In [1]:
import numpy as np
rm = np.random.randint(0, 10, size=(3,3))
im = np.identity(3)
print(f"""
Початкова рандомна матриця: 
{rm}
Початкова матриця ідентичності: 
{im}
Арифметичні операції які здйснюються поелементно:
Додавання
{rm + im + 1} 
Віднімання
{rm - im + 5}
Множення і решта операцій (складні вирази)
{(rm - 5) * (im + 5) }
{rm[rm >= 5]}
""")


Початкова рандомна матриця: 
[[9 2 6]
 [0 7 5]
 [0 2 1]]
Початкова матриця ідентичності: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Арифметичні операції які здйснюються поелементно:
Додавання
[[11.  3.  7.]
 [ 1.  9.  6.]
 [ 1.  3.  3.]] 
Віднімання
[[13.  7. 11.]
 [ 5. 11. 10.]
 [ 5.  7.  5.]]
Множення і решта операцій (складні вирази)
[[ 24. -15.   5.]
 [-25.  12.   0.]
 [-25. -15. -24.]]
[9 6 7 5]



### Трохи про вищу математику

In [2]:
import numpy as np
A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])
print(f"Маємо два масиви:\n A: \n{A} \nB: \n{B}")
R = A * B
print(f"Тут виконується поелементне множення:\n{R}")
R = np.dot(A, B)
print(f"Тут масиви перемножуються як матриці (np.dot):\n{R}")
MA = np.matrix(A)
MB = np.matrix(B)
print(f"""Тут масиви перетворені на матриці і далі перемножуються:
{MA * MB} 
Так само, як і:
{MA.dot(MB)}
""")
rm = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det_rm = np.linalg.det(rm)
print(f"Детермінант матриці rm: {det_rm}")

Маємо два масиви:
 A: 
[[1 2 3]
 [2 2 2]
 [3 3 3]] 
B: 
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут масиви перемножуються як матриці (np.dot):
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]] 
Так само, як і:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]

Детермінант матриці rm: 0.0


### Пробуємо вирівнювати масиви

In [3]:
print(rm.shape, rm)
a1 = np.array([1, 2, 3])
print(a1.shape, a1)
rm + a1
a2 = np.array([ [1], [2], [3] ])
print(a2.shape, a2)
rm + a2
A2 = a2[np.newaxis, :]
print(A2.shape)
rm + A2

(3, 3) [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3,) [1 2 3]
(3, 1) [[1]
 [2]
 [3]]
(1, 3, 1)


array([[[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]]])