### Структуровані масиви даних

In [2]:
%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

Note: you may need to restart the kernel to use updated packages.


### Визначення однорідного масиву - COMPLETED

In [3]:
lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]

A = np.array(lst, dtype=np.int8)
print(f"Отриманий масив має вигляд:\n{repr(A)}")

B = np.array(lst, dtype=np.float16)
print(f"Отриманий масив має вигляд:\n{repr(B)}")

# Завдання 1:
homework("Згадуючи ООП, що робить функція repr?")
print("Функція repr() використовується для отримання строкового представлення об'єкта, яке має бути зручним для представлення об'єкта в коді.")

# Завдання 2:
homework("У чому різниця між масивами A i B?")
print("Різниця між масивами A і B полягає в типах даних: A містить цілі числа типу np.int8 (8-бітні цілі числа), а B містить числа з плаваючою комою типу np.float16 (16-бітні числа з плаваючою комою).")

Отриманий масив має вигляд:
array([[ 3,  8,  9],
       [ 1, -7,  0],
       [ 4, 12,  4]], dtype=int8)
Отриманий масив має вигляд:
array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]], dtype=float16)

>>>>> Згадуючи ООП, що робить функція repr? 

Функція repr() використовується для отримання строкового представлення об'єкта, яке має бути зручним для представлення об'єкта в коді.

>>>>> У чому різниця між масивами A i B? 

Різниця між масивами A і B полягає в типах даних: A містить цілі числа типу np.int8 (8-бітні цілі числа), а B містить числа з плаваючою комою типу np.float16 (16-бітні числа з плаваючою комою).


### Задаємо свій тип даних - COMPLETED

In [4]:
import numpy as np

# Визначення dtype з використанням np.str_ для рядків
dt = np.dtype([('name', np.str_, 20), ('mark', np.int8)])

arr = [
    ("Bohdan", 4),
    ("Marta", 5),
    ("Noname", 0)
]

# Створення масиву з заданим типом даних
C = np.array(arr, dtype=dt)

# Виведення масиву
print(f"Отриманий масив має вигляд:\n{C}")
print(f"Доступитись до певної колонки тепер можна за її іменем: {C['mark']}")

# Завдання 1:
homework = "Як вивести всі імена присутні в даному масиві?"
print("Щоб вивести всі імена з масиву, можна звернутися до колонки 'name':")
print(C['name'])

Отриманий масив має вигляд:
[('Bohdan', 4) ('Marta', 5) ('Noname', 0)]
Доступитись до певної колонки тепер можна за її іменем: [4 5 0]
Щоб вивести всі імена з масиву, можна звернутися до колонки 'name':
['Bohdan' 'Marta' 'Noname']


### Запис та зчитування з файлу, формат CSV - COMPLETED

In [5]:
import numpy as np
import os

# Оновлений dtype з додаванням нового поля 'group'
dt = np.dtype([('name', np.str_, 20), ('mark', np.int8), ('group', np.str_, 10)])

# Початковий масив, додаємо нове поле 'group'
arr = [
    ("Bohdan", 4, "Group1"),
    ("Marta", 5, "Group2"),
    ("Noname", 0, "Group3"),
    ("Антон", 5, "КН-41")
]

# Створення масиву з заданим типом даних
C = np.array(arr, dtype=dt)

# Збереження масиву у файл .npz
np.savez("my_mass.npz", my_mass=C)
D = np.load("my_mass.npz")
print("Прочитаний з файлу: ", D["my_mass"])

# Збереження масиву у CSV файл
filename = "temp.csv"
np.savetxt(filename, C, fmt="%s,%d,%s", header="name,mark,group", delimiter=",")

# Перевірка чи файл створився
print(f"Перевіряємо чи файл {filename} створився: {os.listdir()}")

# Читання CSV файлу
print("Читаємо файл за допомогою оператора with та методу readlines")
with open(filename) as f:
    D = f.readlines()

print(f"Прочитаний файл:\n {D} \n- як бачимо - {len(D)} елементи є стрічками {type(D[0])}.")

# Зчитування значень з файлу у масив
D = np.genfromtxt(filename, dtype=dt, delimiter=",", names=True)
print(f"Зчитане значення з файла:\n {D}, як бачимо - {D.size} елементи це {type(D[0])} \n- вбудований клас бібліотеки numpy.")
print(f"Доступитись до певного елемента можна наступним чином, наприклад імя першого елементу: {D[0]['name']}")

# Читання вашого імені з масиву
your_name = D[D['name'] == "Антон"]['name']
print(f"Ваше ім'я, знайдене у масиві: {your_name[0]}")  # Вивести перший результат

Прочитаний з файлу:  [('Bohdan', 4, 'Group1') ('Marta', 5, 'Group2') ('Noname', 0, 'Group3')
 ('Антон', 5, 'КН-41')]
Перевіряємо чи файл temp.csv створився: ['.git', 'my_mass.npz', 'Practicalappnumdata.ipynb', 'temp.csv']
Читаємо файл за допомогою оператора with та методу readlines
Прочитаний файл:
 ['# name,mark,group\n', 'Bohdan,4,Group1\n', 'Marta,5,Group2\n', 'Noname,0,Group3\n', 'Антон,5,КН-41\n'] 
- як бачимо - 5 елементи є стрічками <class 'str'>.
Зчитане значення з файла:
 [('Bohdan', 4, 'Group1') ('Marta', 5, 'Group2') ('Noname', 0, 'Group3')
 ('Антон', 5, 'КН-41')], як бачимо - 4 елементи це <class 'numpy.void'> 
- вбудований клас бібліотеки numpy.
Доступитись до певного елемента можна наступним чином, наприклад імя першого елементу: Bohdan
Ваше ім'я, знайдене у масиві: Антон


### Операції над масивами

In [6]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

l = (3, 3)

# Створення різних матриць
O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

# Виведення результатів математичних операцій
print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Порівняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")

homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")

# Завдання 1: Створення матриці eye і порівняння на наявність 1
eye_matrix = np.eye(3)
print(f"Матриця eye:\n{eye_matrix}")
comparison_eye = eye_matrix == 1
print(f"Порівняння з 1 (де 1 - це одиничні елементи):\n{comparison_eye}")

# Завдання 2: Віднімання матриці eye від матриці ones
ones_matrix = np.ones((3, 3))
result_matrix = ones_matrix - eye_matrix
print(f"Результат віднімання ones від eye (центральна діагональ з нулями):\n{result_matrix}")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.27570187 0.77548603 0.52104896]
 [0.02363902 0.33912808 0.16805737]
 [0.42856577 0.42308745 0.14286011]]
Ділення:
 [[       inf 0.77548603 0.26052448]
 [       inf 0.33912808 0.08402869]
 [       inf 0.42308745 0.07143006]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Порівняння:
 [[False  True  True]
 [False False False]
 [False False False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 

Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Порівняння з 1 (де 1 - це одиничні елементи):
[[ True False False]
 [False  True False]
 [False False  True]]
Результат віднімання ones від eye (центральна діагональ з нулями):
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


C:\Users\Komp\AppData\Local\Temp\ipykernel_8624\1191290917.py:17: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\Komp\AppData\Local\Temp\ipykernel_8624\1191290917.py:20: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


### Множення матриць

In [7]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


### Вирівнювання розмірностей

In [8]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


### Конкатенація, повторення та зміна форми (shape) - COMPLETED

In [9]:
import numpy as np

# Ініціалізація масивів
D = np.ones(3)
Z = np.zeros((3, 1))

# Додаткові масиви для прикладів
B = np.zeros((3, 3))
C = np.zeros((3, 1))
A = np.arange(12).reshape(3, 4)

# Виведення результатів
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:
{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з масивом B, що має розмірність {B.shape}:
{np.concatenate((B, B))}

Для конкатенації з масивом C:
{C}
де C має розмірність = {C.shape}, потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3, 1)).shape}
В результаті ми можемо виконати конкатенацію:
{np.concatenate((C, D.reshape((3, 1))))}

При повторенні масиву D {D} 2 рази для рядків та 3 для стовпців будемо мати:
{np.tile(D, (2, 3))}

Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}

Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")

# Завдання 1:
homework(f"""
Створіть двовимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив, в якому кількість рядків та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім.
Якщо розмірність масивів не співпадає, використайте reshape.
Створіть кілька двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінування reshape.
Наприклад, перша комбінація це рядок: {np.ones((1, 12))}
""")

import numpy as np

# Створення двовимірного масиву за допомогою arange
A = np.arange(12).reshape(3, 4)  # Створюємо масив 3x4
print(f"Масив A (3x4):\n{A}\n")

# Конкатенація двовимірних масивів по рядках та стовпцях
B = np.ones((3, 4))  # Масив для конкатенації, 3x4

# Конкатенація по рядках
concat_rows = np.concatenate((A, B), axis=0)  # Додаємо рядки
print(f"Конкатенація по рядках (6x4):\n{concat_rows}\n")

# Конкатенація по стовпцях
concat_cols = np.concatenate((A, B), axis=1)  # Додаємо стовпці
print(f"Конкатенація по стовпцях (3x8):\n{concat_cols}\n")

# Повторення масивів
repeat_array = np.tile(A, (2, 3))  # Повторюємо масив A 2 рази по рядках та 3 рази по стовпцях
print(f"Повторення масиву A (6x12):\n{repeat_array}\n")

# Створення масиву з різною кількістю рядків і стовпців
C = np.arange(6).reshape(2, 3)  # Масив 2x3
print(f"Масив C (2x3):\n{C}\n")

# Спроба виконати конкатенацію між A (3x4) і C (2x3)
# Враховуючи різні розміри, для цього використаємо reshape
C_reshaped = C.reshape(3, 2)  # Змінюємо розмірність C на (3x2)
print(f"Масив C після reshape (3x2):\n{C_reshaped}\n")

# Тепер можна виконати конкатенацію
concat_C_A = np.concatenate((A, C_reshaped), axis=1)  # Конкатенуємо по стовпцях (3x6)
print(f"Конкатенація A (3x4) та C (3x2) по стовпцях:\n{concat_C_A}\n")

# Створення масивів з сумарною розмірністю 12
D = np.arange(12).reshape(3, 4)  # Масив 3x4
E = np.ones((2, 6))  # Масив 2x6

# Пошук можливих комбінацій reshape для сумарної розмірності 12
combinations = [
    (12, 1),   # Один рядок, 12 стовпців
    (1, 12),   # Один стовпець, 12 рядків
    (3, 4),    # 3 рядки, 4 стовпці
    (4, 3),    # 4 рядки, 3 стовпці
    (2, 6),    # 2 рядки, 6 стовпців
    (6, 2)     # 6 рядків, 2 стовпці
]

print("Можливі комбінації reshape для розмірності 12:")
for shape in combinations:
    reshaped = np.arange(12).reshape(shape)
    print(f"Розмірність {shape}:\n{reshaped}\n")


При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з масивом B, що має розмірність (3, 3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Для конкатенації з масивом C:
[[0.]
 [0.]
 [0.]]
де C має розмірність = (3, 1), потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
В результаті ми можемо виконати конкатенацію:
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]

При повторенні масиву D [1. 1. 1.] 2 рази для рядків та 3 для стовпців будемо мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]

Також можна перетворити двовимірний масив A розмірністю (3, 4) на рядок: [ 0  1  2  3  4  5  6  7  8  9 10 11] з розмірністю (12,)


>>>>> 
Створіть двови

### Трансформації масивів - COMPLETED

In [10]:
import numpy as np

# Створення масиву
O = np.arange(6).reshape(3, 2)
O_r = O.reshape((2, 3))  # Зміна розмірності
O_f = O.flatten()  # Перетворення на одномірний масив
O_t = O.transpose()  # Транспонування масиву
O_fl = np.flip(O)  # Перевернути масив (по обох осях)
O_fa = np.flip(O, axis=1)  # Перевернути масив по стовпцях

# Виведення результатів
print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

# Завдання 1:
homework(""" 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірність перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")

# 1. Створення вектора з 12 елементів
vector = np.arange(12)
print(f"Вектор:\n{vector}")
print(f"Shape: {vector.shape}, Size: {vector.size}, Ndim: {vector.ndim}\n")

# 2. Зміна розмірності перетворивши вектор у матрицю
matrix = vector.reshape(3, 4)  # Перетворюємо вектор в матрицю 3x4
print(f"Матриця після reshape (3x4):\n{matrix}")
print(f"Shape: {matrix.shape}, Size: {matrix.size}, Ndim: {matrix.ndim}\n")

# 3. Транспонування отриманої матриці
transposed_matrix = matrix.transpose()  # Транспонування матриці
print(f"Транспонована матриця (4x3):\n{transposed_matrix}")
print(f"Shape: {transposed_matrix.shape}, Size: {transposed_matrix.size}, Ndim: {transposed_matrix.ndim}\n")

# 4. Обертання матриці
flipped_matrix = np.flip(transposed_matrix)  # Перевертаємо матрицю (по обох осях)
print(f"Перевернута матриця:\n{flipped_matrix}")
print(f"Shape: {flipped_matrix.shape}, Size: {flipped_matrix.size}, Ndim: {flipped_matrix.ndim}\n")

# 5. Перетворення багатовимірного масиву назад у вектор
flattened_vector = flipped_matrix.flatten()  # Перетворюємо матрицю назад у вектор
print(f"Вектор після перетворення з матриці:\n{flattened_vector}")
print(f"Shape: {flattened_vector.shape}, Size: {flattened_vector.size}, Ndim: {flattened_vector.ndim}\n")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>>  
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірність перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 

Вектор:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,), Size: 12, Ndim: 1

Матриця після reshape (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4), Size: 12, Ndim: 2

Тр